# src/compiler.gni
set(angle_translator_exported_headers
    include/GLSLANG/ShaderLang.h
    include/GLSLANG/ShaderVars.h
    src/compiler/translator/blocklayout.h
    src/compiler/translator/hlsl/blocklayoutHLSL.h
)

set(angle_translator_sources
    include/EGL/egl.h
    include/EGL/eglext.h
    include/EGL/eglplatform.h
    include/GLES2/gl2.h
    include/GLES2/gl2ext.h
    include/GLES2/gl2platform.h
    include/GLES3/gl3.h
    include/GLES3/gl31.h
    include/GLES3/gl32.h
    include/GLES3/gl3platform.h
    include/KHR/khrplatform.h
    include/angle_gl.h
    src/compiler/translator/AsNode.h
    src/compiler/translator/BaseTypes.cpp
    src/compiler/translator/BaseTypes.h
    src/compiler/translator/BuiltInFunctionEmulator.cpp
    src/compiler/translator/BuiltInFunctionEmulator.h
    src/compiler/translator/CallDAG.cpp
    src/compiler/translator/CallDAG.h
    src/compiler/translator/CodeGen.cpp
    src/compiler/translator/CollectVariables.cpp
    src/compiler/translator/CollectVariables.h
    src/compiler/translator/Common.h
    src/compiler/translator/Compiler.cpp
    src/compiler/translator/Compiler.h
    src/compiler/translator/ConstantUnion.cpp
    src/compiler/translator/ConstantUnion.h
    src/compiler/translator/Declarator.cpp
    src/compiler/translator/Declarator.h
    src/compiler/translator/Diagnostics.cpp
    src/compiler/translator/Diagnostics.h
    src/compiler/translator/DirectiveHandler.cpp
    src/compiler/translator/DirectiveHandler.h
    src/compiler/translator/ExtensionBehavior.cpp
    src/compiler/translator/ExtensionBehavior.h
    src/compiler/translator/FlagStd140Structs.cpp
    src/compiler/translator/FlagStd140Structs.h
    src/compiler/translator/FunctionLookup.cpp
    src/compiler/translator/FunctionLookup.h
    src/compiler/translator/HashNames.cpp
    src/compiler/translator/HashNames.h
    src/compiler/translator/ImmutableString.h
    src/compiler/translator/ImmutableStringBuilder.cpp
    src/compiler/translator/ImmutableStringBuilder.h
    src/compiler/translator/InfoSink.cpp
    src/compiler/translator/InfoSink.h
    src/compiler/translator/Initialize.cpp
    src/compiler/translator/Initialize.h
    src/compiler/translator/InitializeDll.cpp
    src/compiler/translator/InitializeDll.h
    src/compiler/translator/InitializeGlobals.h
    src/compiler/translator/IntermNode.cpp
    src/compiler/translator/IntermNode.h
    src/compiler/translator/IntermRebuild.cpp
    src/compiler/translator/IntermRebuild.h
    src/compiler/translator/IsASTDepthBelowLimit.cpp
    src/compiler/translator/IsASTDepthBelowLimit.h
    src/compiler/translator/Name.cpp
    src/compiler/translator/Name.h
    src/compiler/translator/NodeType.h
    src/compiler/translator/Operator.cpp
    src/compiler/translator/Operator_autogen.h
    src/compiler/translator/OutputTree.cpp
    src/compiler/translator/OutputTree.h
    src/compiler/translator/ParseContext.cpp
    src/compiler/translator/ParseContext.h
    src/compiler/translator/PoolAlloc.cpp
    src/compiler/translator/PoolAlloc.h
    src/compiler/translator/Pragma.h
    src/compiler/translator/QualifierTypes.cpp
    src/compiler/translator/QualifierTypes.h
    src/compiler/translator/Severity.h
    src/compiler/translator/ShaderLang.cpp
    src/compiler/translator/ShaderVars.cpp
    src/compiler/translator/StaticType.h
    src/compiler/translator/Symbol.cpp
    src/compiler/translator/Symbol.h
    src/compiler/translator/SymbolTable.cpp
    src/compiler/translator/SymbolTable.h
    src/compiler/translator/SymbolTable_autogen.h
    src/compiler/translator/SymbolUniqueId.cpp
    src/compiler/translator/SymbolUniqueId.h
    src/compiler/translator/Types.cpp
    src/compiler/translator/Types.h
    src/compiler/translator/ValidateAST.cpp
    src/compiler/translator/ValidateAST.h
    src/compiler/translator/ValidateBarrierFunctionCall.cpp
    src/compiler/translator/ValidateBarrierFunctionCall.h
    src/compiler/translator/ValidateClipCullDistance.cpp
    src/compiler/translator/ValidateClipCullDistance.h
    src/compiler/translator/ValidateGlobalInitializer.cpp
    src/compiler/translator/ValidateGlobalInitializer.h
    src/compiler/translator/ValidateLimitations.cpp
    src/compiler/translator/ValidateLimitations.h
    src/compiler/translator/ValidateMaxParameters.cpp
    src/compiler/translator/ValidateMaxParameters.h
    src/compiler/translator/ValidateOutputs.cpp
    src/compiler/translator/ValidateOutputs.h
    src/compiler/translator/ValidateSwitch.cpp
    src/compiler/translator/ValidateSwitch.h
    src/compiler/translator/ValidateTypeSizeLimitations.cpp
    src/compiler/translator/ValidateTypeSizeLimitations.h
    src/compiler/translator/ValidateVaryingLocations.cpp
    src/compiler/translator/ValidateVaryingLocations.h
    src/compiler/translator/VariablePacker.cpp
    src/compiler/translator/VariablePacker.h
    src/compiler/translator/blocklayout.cpp
    src/compiler/translator/glsl/TranslatorESSL.h
    src/compiler/translator/glsl/TranslatorGLSL.h
    src/compiler/translator/glsl/VersionGLSL.h
    src/compiler/translator/glslang.h
    src/compiler/translator/glslang_lex_autogen.cpp
    src/compiler/translator/glslang_tab_autogen.cpp
    src/compiler/translator/glslang_tab_autogen.h
    src/compiler/translator/hlsl/TranslatorHLSL.h
    src/compiler/translator/length_limits.h
    src/compiler/translator/msl/DriverUniformMetal.h
    src/compiler/translator/msl/TranslatorMSL.h
    src/compiler/translator/null/TranslatorNULL.h
    src/compiler/translator/spirv/TranslatorSPIRV.h
    src/compiler/translator/tree_ops/ClampFragDepth.cpp
    src/compiler/translator/tree_ops/ClampFragDepth.h
    src/compiler/translator/tree_ops/ClampIndirectIndices.cpp
    src/compiler/translator/tree_ops/ClampIndirectIndices.h
    src/compiler/translator/tree_ops/ClampPointSize.cpp
    src/compiler/translator/tree_ops/ClampPointSize.h
    src/compiler/translator/tree_ops/DeclareAndInitBuiltinsForInstancedMultiview.cpp
    src/compiler/translator/tree_ops/DeclareAndInitBuiltinsForInstancedMultiview.h
    src/compiler/translator/tree_ops/DeclarePerVertexBlocks.cpp
    src/compiler/translator/tree_ops/DeclarePerVertexBlocks.h
    src/compiler/translator/tree_ops/DeferGlobalInitializers.cpp
    src/compiler/translator/tree_ops/DeferGlobalInitializers.h
    src/compiler/translator/tree_ops/EmulateGLFragColorBroadcast.cpp
    src/compiler/translator/tree_ops/EmulateGLFragColorBroadcast.h
    src/compiler/translator/tree_ops/EmulateMultiDrawShaderBuiltins.cpp
    src/compiler/translator/tree_ops/EmulateMultiDrawShaderBuiltins.h
    src/compiler/translator/tree_ops/FoldExpressions.cpp
    src/compiler/translator/tree_ops/FoldExpressions.h
    src/compiler/translator/tree_ops/ForcePrecisionQualifier.cpp
    src/compiler/translator/tree_ops/ForcePrecisionQualifier.h
    src/compiler/translator/tree_ops/InitializeVariables.cpp
    src/compiler/translator/tree_ops/InitializeVariables.h
    src/compiler/translator/tree_ops/MonomorphizeUnsupportedFunctions.cpp
    src/compiler/translator/tree_ops/MonomorphizeUnsupportedFunctions.h
    src/compiler/translator/tree_ops/PreTransformTextureCubeGradDerivatives.cpp
    src/compiler/translator/tree_ops/PreTransformTextureCubeGradDerivatives.h
    src/compiler/translator/tree_ops/PruneEmptyCases.cpp
    src/compiler/translator/tree_ops/PruneEmptyCases.h
    src/compiler/translator/tree_ops/PruneInfiniteLoops.cpp
    src/compiler/translator/tree_ops/PruneInfiniteLoops.h
    src/compiler/translator/tree_ops/PruneNoOps.cpp
    src/compiler/translator/tree_ops/PruneNoOps.h
    src/compiler/translator/tree_ops/RecordConstantPrecision.cpp
    src/compiler/translator/tree_ops/RecordConstantPrecision.h
    src/compiler/translator/tree_ops/RemoveArrayLengthMethod.cpp
    src/compiler/translator/tree_ops/RemoveArrayLengthMethod.h
    src/compiler/translator/tree_ops/RemoveAtomicCounterBuiltins.cpp
    src/compiler/translator/tree_ops/RemoveAtomicCounterBuiltins.h
    src/compiler/translator/tree_ops/RemoveDynamicIndexing.cpp
    src/compiler/translator/tree_ops/RemoveDynamicIndexing.h
    src/compiler/translator/tree_ops/RemoveInactiveInterfaceVariables.cpp
    src/compiler/translator/tree_ops/RemoveInactiveInterfaceVariables.h
    src/compiler/translator/tree_ops/RemoveInvariantDeclaration.cpp
    src/compiler/translator/tree_ops/RemoveInvariantDeclaration.h
    src/compiler/translator/tree_ops/RemoveUnreferencedVariables.cpp
    src/compiler/translator/tree_ops/RemoveUnusedFramebufferFetch.cpp
    src/compiler/translator/tree_ops/RemoveUnusedFramebufferFetch.h
    src/compiler/translator/tree_ops/RescopeGlobalVariables.cpp
    src/compiler/translator/tree_ops/RescopeGlobalVariables.h
    src/compiler/translator/tree_ops/RewriteArrayOfArrayOfOpaqueUniforms.cpp
    src/compiler/translator/tree_ops/RewriteArrayOfArrayOfOpaqueUniforms.h
    src/compiler/translator/tree_ops/RewriteAtomicCounters.cpp
    src/compiler/translator/tree_ops/RewriteAtomicCounters.h
    src/compiler/translator/tree_ops/RewriteDfdy.cpp
    src/compiler/translator/tree_ops/RewriteDfdy.h
    src/compiler/translator/tree_ops/RewritePixelLocalStorage.cpp
    src/compiler/translator/tree_ops/RewritePixelLocalStorage.h
    src/compiler/translator/tree_ops/RewriteStructSamplers.cpp
    src/compiler/translator/tree_ops/RewriteStructSamplers.h
    src/compiler/translator/tree_ops/RewriteTexelFetchOffset.cpp
    src/compiler/translator/tree_ops/RewriteTexelFetchOffset.h
    src/compiler/translator/tree_ops/SeparateDeclarations.cpp
    src/compiler/translator/tree_ops/SeparateDeclarations.h
    src/compiler/translator/tree_ops/SeparateStructFromUniformDeclarations.cpp
    src/compiler/translator/tree_ops/SeparateStructFromUniformDeclarations.h
    src/compiler/translator/tree_ops/SimplifyLoopConditions.cpp
    src/compiler/translator/tree_ops/SimplifyLoopConditions.h
    src/compiler/translator/tree_ops/SplitSequenceOperator.cpp
    src/compiler/translator/tree_ops/SplitSequenceOperator.h
    src/compiler/translator/tree_ops/glsl/RegenerateStructNames.h
    src/compiler/translator/tree_ops/glsl/RewriteRepeatedAssignToSwizzled.h
    src/compiler/translator/tree_ops/glsl/ScalarizeVecAndMatConstructorArgs.h
    src/compiler/translator/tree_ops/glsl/UseInterfaceBlockFields.h
    src/compiler/translator/tree_ops/glsl/apple/AddAndTrueToLoopCondition.h
    src/compiler/translator/tree_ops/glsl/apple/RewriteDoWhile.h
    src/compiler/translator/tree_ops/glsl/apple/RewriteRowMajorMatrices.h
    src/compiler/translator/tree_ops/glsl/apple/RewriteUnaryMinusOperatorFloat.h
    src/compiler/translator/tree_ops/glsl/apple/UnfoldShortCircuitAST.h
    src/compiler/translator/tree_util/BuiltIn.h
    src/compiler/translator/tree_util/BuiltIn_autogen.h
    src/compiler/translator/tree_util/DriverUniform.cpp
    src/compiler/translator/tree_util/DriverUniform.h
    src/compiler/translator/tree_util/FindFunction.cpp
    src/compiler/translator/tree_util/FindFunction.h
    src/compiler/translator/tree_util/FindMain.cpp
    src/compiler/translator/tree_util/FindMain.h
    src/compiler/translator/tree_util/FindPreciseNodes.cpp
    src/compiler/translator/tree_util/FindPreciseNodes.h
    src/compiler/translator/tree_util/FindSymbolNode.cpp
    src/compiler/translator/tree_util/FindSymbolNode.h
    src/compiler/translator/tree_util/IntermNodePatternMatcher.cpp
    src/compiler/translator/tree_util/IntermNodePatternMatcher.h
    src/compiler/translator/tree_util/IntermNode_util.cpp
    src/compiler/translator/tree_util/IntermNode_util.h
    src/compiler/translator/tree_util/IntermTraverse.cpp
    src/compiler/translator/tree_util/IntermTraverse.h
    src/compiler/translator/tree_util/NodeSearch.h
    src/compiler/translator/tree_util/ReplaceArrayOfMatrixVarying.cpp
    src/compiler/translator/tree_util/ReplaceArrayOfMatrixVarying.h
    src/compiler/translator/tree_util/ReplaceClipCullDistanceVariable.cpp
    src/compiler/translator/tree_util/ReplaceClipCullDistanceVariable.h
    src/compiler/translator/tree_util/ReplaceShadowingVariables.cpp
    src/compiler/translator/tree_util/ReplaceShadowingVariables.h
    src/compiler/translator/tree_util/ReplaceVariable.cpp
    src/compiler/translator/tree_util/ReplaceVariable.h
    src/compiler/translator/tree_util/RewriteSampleMaskVariable.cpp
    src/compiler/translator/tree_util/RewriteSampleMaskVariable.h
    src/compiler/translator/tree_util/RunAtTheBeginningOfShader.cpp
    src/compiler/translator/tree_util/RunAtTheBeginningOfShader.h
    src/compiler/translator/tree_util/RunAtTheEndOfShader.cpp
    src/compiler/translator/tree_util/RunAtTheEndOfShader.h
    src/compiler/translator/tree_util/SpecializationConstant.cpp
    src/compiler/translator/tree_util/SpecializationConstant.h
    src/compiler/translator/tree_util/Visit.h
    src/compiler/translator/util.cpp
    src/compiler/translator/util.h
    src/compiler/translator/wgsl/TranslatorWGSL.h
)

set(angle_translator_glsl_base_sources
    src/compiler/translator/glsl/OutputGLSLBase.cpp
    src/compiler/translator/glsl/OutputGLSLBase.h
)

set(angle_translator_glsl_and_vulkan_base_sources
    src/compiler/translator/glsl/OutputGLSL.cpp
    src/compiler/translator/glsl/OutputGLSL.h
)

set(angle_translator_essl_sources
    src/compiler/translator/glsl/OutputESSL.cpp
    src/compiler/translator/glsl/OutputESSL.h
    src/compiler/translator/glsl/TranslatorESSL.cpp
)

set(angle_translator_glsl_sources
    src/compiler/translator/glsl/BuiltInFunctionEmulatorGLSL.cpp
    src/compiler/translator/glsl/BuiltInFunctionEmulatorGLSL.h
    src/compiler/translator/glsl/ExtensionGLSL.cpp
    src/compiler/translator/glsl/ExtensionGLSL.h
    src/compiler/translator/glsl/TranslatorGLSL.cpp
    src/compiler/translator/glsl/VersionGLSL.cpp
    src/compiler/translator/tree_ops/glsl/RegenerateStructNames.cpp
    src/compiler/translator/tree_ops/glsl/RewriteRepeatedAssignToSwizzled.cpp
    src/compiler/translator/tree_ops/glsl/ScalarizeVecAndMatConstructorArgs.cpp
    src/compiler/translator/tree_ops/glsl/UseInterfaceBlockFields.cpp
)

set(angle_translator_glsl_apple_sources
    src/compiler/translator/tree_ops/glsl/apple/AddAndTrueToLoopCondition.cpp
    src/compiler/translator/tree_ops/glsl/apple/RewriteDoWhile.cpp
    src/compiler/translator/tree_ops/glsl/apple/RewriteRowMajorMatrices.cpp
    src/compiler/translator/tree_ops/glsl/apple/RewriteUnaryMinusOperatorFloat.cpp
    src/compiler/translator/tree_ops/glsl/apple/UnfoldShortCircuitAST.cpp
)

set(angle_translator_hlsl_sources
    src/compiler/translator/hlsl/ASTMetadataHLSL.cpp
    src/compiler/translator/hlsl/ASTMetadataHLSL.h
    src/compiler/translator/hlsl/AtomicCounterFunctionHLSL.cpp
    src/compiler/translator/hlsl/AtomicCounterFunctionHLSL.h
    src/compiler/translator/hlsl/BuiltInFunctionEmulatorHLSL.cpp
    src/compiler/translator/hlsl/BuiltInFunctionEmulatorHLSL.h
    src/compiler/translator/hlsl/ImageFunctionHLSL.cpp
    src/compiler/translator/hlsl/ImageFunctionHLSL.h
    src/compiler/translator/hlsl/OutputHLSL.cpp
    src/compiler/translator/hlsl/OutputHLSL.h
    src/compiler/translator/hlsl/ResourcesHLSL.cpp
    src/compiler/translator/hlsl/ResourcesHLSL.h
    src/compiler/translator/hlsl/ShaderStorageBlockFunctionHLSL.cpp
    src/compiler/translator/hlsl/ShaderStorageBlockFunctionHLSL.h
    src/compiler/translator/hlsl/ShaderStorageBlockOutputHLSL.cpp
    src/compiler/translator/hlsl/ShaderStorageBlockOutputHLSL.h
    src/compiler/translator/hlsl/StructureHLSL.cpp
    src/compiler/translator/hlsl/StructureHLSL.h
    src/compiler/translator/hlsl/TextureFunctionHLSL.cpp
    src/compiler/translator/hlsl/TextureFunctionHLSL.h
    src/compiler/translator/hlsl/TranslatorHLSL.cpp
    src/compiler/translator/hlsl/UtilsHLSL.cpp
    src/compiler/translator/hlsl/UtilsHLSL.h
    src/compiler/translator/hlsl/blocklayoutHLSL.cpp
    src/compiler/translator/hlsl/emulated_builtin_functions_hlsl_autogen.cpp
    src/compiler/translator/tree_ops/hlsl/AddDefaultReturnStatements.cpp
    src/compiler/translator/tree_ops/hlsl/AddDefaultReturnStatements.h
    src/compiler/translator/tree_ops/hlsl/AggregateAssignArraysInSSBOs.cpp
    src/compiler/translator/tree_ops/hlsl/AggregateAssignArraysInSSBOs.h
    src/compiler/translator/tree_ops/hlsl/AggregateAssignStructsInSSBOs.cpp
    src/compiler/translator/tree_ops/hlsl/AggregateAssignStructsInSSBOs.h
    src/compiler/translator/tree_ops/hlsl/ArrayReturnValueToOutParameter.cpp
    src/compiler/translator/tree_ops/hlsl/ArrayReturnValueToOutParameter.h
    src/compiler/translator/tree_ops/hlsl/BreakVariableAliasingInInnerLoops.cpp
    src/compiler/translator/tree_ops/hlsl/BreakVariableAliasingInInnerLoops.h
    src/compiler/translator/tree_ops/hlsl/ExpandIntegerPowExpressions.cpp
    src/compiler/translator/tree_ops/hlsl/ExpandIntegerPowExpressions.h
    src/compiler/translator/tree_ops/hlsl/RecordUniformBlocksWithLargeArrayMember.cpp
    src/compiler/translator/tree_ops/hlsl/RecordUniformBlocksWithLargeArrayMember.h
    src/compiler/translator/tree_ops/hlsl/RemoveSwitchFallThrough.cpp
    src/compiler/translator/tree_ops/hlsl/RemoveSwitchFallThrough.h
    src/compiler/translator/tree_ops/hlsl/RewriteAtomicFunctionExpressions.cpp
    src/compiler/translator/tree_ops/hlsl/RewriteAtomicFunctionExpressions.h
    src/compiler/translator/tree_ops/hlsl/RewriteElseBlocks.cpp
    src/compiler/translator/tree_ops/hlsl/RewriteElseBlocks.h
    src/compiler/translator/tree_ops/hlsl/RewriteExpressionsWithShaderStorageBlock.cpp
    src/compiler/translator/tree_ops/hlsl/RewriteExpressionsWithShaderStorageBlock.h
    src/compiler/translator/tree_ops/hlsl/RewriteUnaryMinusOperatorInt.cpp
    src/compiler/translator/tree_ops/hlsl/RewriteUnaryMinusOperatorInt.h
    src/compiler/translator/tree_ops/hlsl/SeparateArrayConstructorStatements.cpp
    src/compiler/translator/tree_ops/hlsl/SeparateArrayConstructorStatements.h
    src/compiler/translator/tree_ops/hlsl/SeparateArrayInitialization.cpp
    src/compiler/translator/tree_ops/hlsl/SeparateArrayInitialization.h
    src/compiler/translator/tree_ops/hlsl/SeparateExpressionsReturningArrays.cpp
    src/compiler/translator/tree_ops/hlsl/SeparateExpressionsReturningArrays.h
    src/compiler/translator/tree_ops/hlsl/UnfoldShortCircuitToIf.cpp
    src/compiler/translator/tree_ops/hlsl/UnfoldShortCircuitToIf.h
    src/compiler/translator/tree_ops/hlsl/WrapSwitchStatementsInBlocks.cpp
    src/compiler/translator/tree_ops/hlsl/WrapSwitchStatementsInBlocks.h
)

set(angle_translator_lib_spirv_sources
    src/compiler/translator/spirv/BuildSPIRV.cpp
    src/compiler/translator/spirv/BuildSPIRV.h
    src/compiler/translator/spirv/BuiltinsWorkaround.cpp
    src/compiler/translator/spirv/BuiltinsWorkaround.h
    src/compiler/translator/spirv/OutputSPIRV.cpp
    src/compiler/translator/spirv/OutputSPIRV.h
    src/compiler/translator/spirv/TranslatorSPIRV.cpp
    src/compiler/translator/tree_ops/spirv/ClampGLLayer.cpp
    src/compiler/translator/tree_ops/spirv/ClampGLLayer.h
    src/compiler/translator/tree_ops/spirv/EmulateAdvancedBlendEquations.cpp
    src/compiler/translator/tree_ops/spirv/EmulateAdvancedBlendEquations.h
    src/compiler/translator/tree_ops/spirv/EmulateDithering.cpp
    src/compiler/translator/tree_ops/spirv/EmulateDithering.h
    src/compiler/translator/tree_ops/spirv/EmulateFragColorData.cpp
    src/compiler/translator/tree_ops/spirv/EmulateFragColorData.h
    src/compiler/translator/tree_ops/spirv/EmulateFramebufferFetch.cpp
    src/compiler/translator/tree_ops/spirv/EmulateFramebufferFetch.h
    src/compiler/translator/tree_ops/spirv/EmulateYUVBuiltIns.cpp
    src/compiler/translator/tree_ops/spirv/EmulateYUVBuiltIns.h
    src/compiler/translator/tree_ops/spirv/FlagSamplersWithTexelFetch.cpp
    src/compiler/translator/tree_ops/spirv/FlagSamplersWithTexelFetch.h
    src/compiler/translator/tree_ops/spirv/ReswizzleYUVOps.cpp
    src/compiler/translator/tree_ops/spirv/ReswizzleYUVOps.h
    src/compiler/translator/tree_ops/spirv/RewriteInterpolateAtOffset.cpp
    src/compiler/translator/tree_ops/spirv/RewriteInterpolateAtOffset.h
    src/compiler/translator/tree_ops/spirv/RewriteR32fImages.cpp
    src/compiler/translator/tree_ops/spirv/RewriteR32fImages.h
)

set(angle_translator_essl_symbol_table_sources
    src/compiler/translator/ImmutableString_autogen.cpp
    src/compiler/translator/SymbolTable_autogen.cpp
)

set(angle_translator_lib_msl_sources
    src/compiler/translator/msl/AstHelpers.cpp
    src/compiler/translator/msl/AstHelpers.h
    src/compiler/translator/msl/ConstantNames.cpp
    src/compiler/translator/msl/DebugSink.h
    src/compiler/translator/msl/DiscoverDependentFunctions.cpp
    src/compiler/translator/msl/DiscoverDependentFunctions.h
    src/compiler/translator/msl/DiscoverEnclosingFunctionTraverser.cpp
    src/compiler/translator/msl/DiscoverEnclosingFunctionTraverser.h
    src/compiler/translator/msl/DriverUniformMetal.cpp
    src/compiler/translator/msl/EmitMetal.cpp
    src/compiler/translator/msl/EmitMetal.h
    src/compiler/translator/msl/IdGen.cpp
    src/compiler/translator/msl/IdGen.h
    src/compiler/translator/msl/Layout.cpp
    src/compiler/translator/msl/Layout.h
    src/compiler/translator/msl/MapFunctionsToDefinitions.cpp
    src/compiler/translator/msl/MapFunctionsToDefinitions.h
    src/compiler/translator/msl/MapSymbols.cpp
    src/compiler/translator/msl/MapSymbols.h
    src/compiler/translator/msl/ModifyStruct.cpp
    src/compiler/translator/msl/ModifyStruct.h
    src/compiler/translator/msl/Pipeline.cpp
    src/compiler/translator/msl/Pipeline.h
    src/compiler/translator/msl/ProgramPrelude.cpp
    src/compiler/translator/msl/ProgramPrelude.h
    src/compiler/translator/msl/Reference.h
    src/compiler/translator/msl/RewritePipelines.cpp
    src/compiler/translator/msl/RewritePipelines.h
    src/compiler/translator/msl/SkippingTraverser.h
    src/compiler/translator/msl/SymbolEnv.cpp
    src/compiler/translator/msl/SymbolEnv.h
    src/compiler/translator/msl/ToposortStructs.cpp
    src/compiler/translator/msl/ToposortStructs.h
    src/compiler/translator/msl/TranslatorMSL.cpp
    src/compiler/translator/msl/UtilsMSL.cpp
    src/compiler/translator/msl/UtilsMSL.h
    src/compiler/translator/tree_ops/msl/AddExplicitTypeCasts.cpp
    src/compiler/translator/tree_ops/msl/AddExplicitTypeCasts.h
    src/compiler/translator/tree_ops/msl/ConvertUnsupportedConstructorsToFunctionCalls.cpp
    src/compiler/translator/tree_ops/msl/ConvertUnsupportedConstructorsToFunctionCalls.h
    src/compiler/translator/tree_ops/msl/FixTypeConstructors.cpp
    src/compiler/translator/tree_ops/msl/FixTypeConstructors.h
    src/compiler/translator/tree_ops/msl/GuardFragDepthWrite.cpp
    src/compiler/translator/tree_ops/msl/GuardFragDepthWrite.h
    src/compiler/translator/tree_ops/msl/HoistConstants.cpp
    src/compiler/translator/tree_ops/msl/HoistConstants.h
    src/compiler/translator/tree_ops/msl/IntroduceVertexIndexID.cpp
    src/compiler/translator/tree_ops/msl/IntroduceVertexIndexID.h
    src/compiler/translator/tree_ops/msl/ReduceInterfaceBlocks.cpp
    src/compiler/translator/tree_ops/msl/ReduceInterfaceBlocks.h
    src/compiler/translator/tree_ops/msl/RewriteCaseDeclarations.cpp
    src/compiler/translator/tree_ops/msl/RewriteCaseDeclarations.h
    src/compiler/translator/tree_ops/msl/RewriteInterpolants.cpp
    src/compiler/translator/tree_ops/msl/RewriteInterpolants.h
    src/compiler/translator/tree_ops/msl/RewriteOutArgs.cpp
    src/compiler/translator/tree_ops/msl/RewriteOutArgs.h
    src/compiler/translator/tree_ops/msl/RewriteUnaddressableReferences.cpp
    src/compiler/translator/tree_ops/msl/RewriteUnaddressableReferences.h
    src/compiler/translator/tree_ops/msl/SeparateCompoundExpressions.cpp
    src/compiler/translator/tree_ops/msl/SeparateCompoundExpressions.h
    src/compiler/translator/tree_ops/msl/TransposeRowMajorMatrices.cpp
    src/compiler/translator/tree_ops/msl/TransposeRowMajorMatrices.h
    src/compiler/translator/tree_ops/msl/WrapMain.cpp
    src/compiler/translator/tree_ops/msl/WrapMain.h
)

set(angle_translator_lib_wgsl_sources
    src/compiler/translator/wgsl/OutputUniformBlocks.cpp
    src/compiler/translator/wgsl/OutputUniformBlocks.h
    src/compiler/translator/wgsl/RewritePipelineVariables.cpp
    src/compiler/translator/wgsl/RewritePipelineVariables.h
    src/compiler/translator/wgsl/TranslatorWGSL.cpp
    src/compiler/translator/wgsl/Utils.cpp
    src/compiler/translator/wgsl/Utils.h
)

set(angle_preprocessor_sources
    src/compiler/preprocessor/DiagnosticsBase.cpp
    src/compiler/preprocessor/DiagnosticsBase.h
    src/compiler/preprocessor/DirectiveHandlerBase.cpp
    src/compiler/preprocessor/DirectiveHandlerBase.h
    src/compiler/preprocessor/DirectiveParser.cpp
    src/compiler/preprocessor/DirectiveParser.h
    src/compiler/preprocessor/ExpressionParser.h
    src/compiler/preprocessor/Input.cpp
    src/compiler/preprocessor/Input.h
    src/compiler/preprocessor/Lexer.cpp
    src/compiler/preprocessor/Lexer.h
    src/compiler/preprocessor/Macro.cpp
    src/compiler/preprocessor/Macro.h
    src/compiler/preprocessor/MacroExpander.cpp
    src/compiler/preprocessor/MacroExpander.h
    src/compiler/preprocessor/Preprocessor.cpp
    src/compiler/preprocessor/Preprocessor.h
    src/compiler/preprocessor/SourceLocation.h
    src/compiler/preprocessor/Token.cpp
    src/compiler/preprocessor/Token.h
    src/compiler/preprocessor/Tokenizer.h
    src/compiler/preprocessor/numeric_lex.h
    src/compiler/preprocessor/preprocessor_lex_autogen.cpp
    src/compiler/preprocessor/preprocessor_tab_autogen.cpp
)

# src/libANGLE/renderer/vulkan/vulkan_backend.gni

set(angle_vulkan_backend_sources
    src/libANGLE/renderer/vulkan/AllocatorHelperPool.cpp
    src/libANGLE/renderer/vulkan/AllocatorHelperPool.h
    src/libANGLE/renderer/vulkan/AllocatorHelperRing.cpp
    src/libANGLE/renderer/vulkan/AllocatorHelperRing.h
    src/libANGLE/renderer/vulkan/BufferVk.cpp
    src/libANGLE/renderer/vulkan/BufferVk.h
    src/libANGLE/renderer/vulkan/CommandQueue.cpp
    src/libANGLE/renderer/vulkan/CommandQueue.h
    src/libANGLE/renderer/vulkan/CompilerVk.cpp
    src/libANGLE/renderer/vulkan/CompilerVk.h
    src/libANGLE/renderer/vulkan/ContextVk.cpp
    src/libANGLE/renderer/vulkan/ContextVk.h
    src/libANGLE/renderer/vulkan/DebugAnnotatorVk.cpp
    src/libANGLE/renderer/vulkan/DebugAnnotatorVk.h
    src/libANGLE/renderer/vulkan/DeviceVk.cpp
    src/libANGLE/renderer/vulkan/DeviceVk.h
    src/libANGLE/renderer/vulkan/DisplayVk.cpp
    src/libANGLE/renderer/vulkan/DisplayVk.h
    src/libANGLE/renderer/vulkan/DisplayVk_api.h
    src/libANGLE/renderer/vulkan/FenceNVVk.cpp
    src/libANGLE/renderer/vulkan/FenceNVVk.h
    src/libANGLE/renderer/vulkan/FramebufferVk.cpp
    src/libANGLE/renderer/vulkan/FramebufferVk.h
    src/libANGLE/renderer/vulkan/ImageVk.cpp
    src/libANGLE/renderer/vulkan/ImageVk.h
    src/libANGLE/renderer/vulkan/MemoryObjectVk.cpp
    src/libANGLE/renderer/vulkan/MemoryObjectVk.h
    src/libANGLE/renderer/vulkan/MemoryTracking.cpp
    src/libANGLE/renderer/vulkan/MemoryTracking.h
    src/libANGLE/renderer/vulkan/OverlayVk.cpp
    src/libANGLE/renderer/vulkan/OverlayVk.h
    src/libANGLE/renderer/vulkan/PersistentCommandPool.cpp
    src/libANGLE/renderer/vulkan/PersistentCommandPool.h
    src/libANGLE/renderer/vulkan/ProgramExecutableVk.cpp
    src/libANGLE/renderer/vulkan/ProgramExecutableVk.h
    src/libANGLE/renderer/vulkan/ProgramPipelineVk.cpp
    src/libANGLE/renderer/vulkan/ProgramPipelineVk.h
    src/libANGLE/renderer/vulkan/ProgramVk.cpp
    src/libANGLE/renderer/vulkan/ProgramVk.h
    src/libANGLE/renderer/vulkan/QueryVk.cpp
    src/libANGLE/renderer/vulkan/QueryVk.h
    src/libANGLE/renderer/vulkan/RenderTargetVk.cpp
    src/libANGLE/renderer/vulkan/RenderTargetVk.h
    src/libANGLE/renderer/vulkan/RenderbufferVk.cpp
    src/libANGLE/renderer/vulkan/RenderbufferVk.h
    src/libANGLE/renderer/vulkan/SamplerVk.cpp
    src/libANGLE/renderer/vulkan/SamplerVk.h
    src/libANGLE/renderer/vulkan/SecondaryCommandBuffer.cpp
    src/libANGLE/renderer/vulkan/SecondaryCommandBuffer.h
    src/libANGLE/renderer/vulkan/SecondaryCommandPool.cpp
    src/libANGLE/renderer/vulkan/SecondaryCommandPool.h
    src/libANGLE/renderer/vulkan/SemaphoreVk.cpp
    src/libANGLE/renderer/vulkan/SemaphoreVk.h
    src/libANGLE/renderer/vulkan/ShaderInterfaceVariableInfoMap.cpp
    src/libANGLE/renderer/vulkan/ShaderInterfaceVariableInfoMap.h
    src/libANGLE/renderer/vulkan/ShaderVk.cpp
    src/libANGLE/renderer/vulkan/ShaderVk.h
    src/libANGLE/renderer/vulkan/ShareGroupVk.cpp
    src/libANGLE/renderer/vulkan/ShareGroupVk.h
    src/libANGLE/renderer/vulkan/Suballocation.cpp
    src/libANGLE/renderer/vulkan/Suballocation.h
    src/libANGLE/renderer/vulkan/SurfaceVk.cpp
    src/libANGLE/renderer/vulkan/SurfaceVk.h
    src/libANGLE/renderer/vulkan/SyncVk.cpp
    src/libANGLE/renderer/vulkan/SyncVk.h
    src/libANGLE/renderer/vulkan/TextureVk.cpp
    src/libANGLE/renderer/vulkan/TextureVk.h
    src/libANGLE/renderer/vulkan/TransformFeedbackVk.cpp
    src/libANGLE/renderer/vulkan/TransformFeedbackVk.h
    src/libANGLE/renderer/vulkan/UtilsVk.cpp
    src/libANGLE/renderer/vulkan/UtilsVk.h
    src/libANGLE/renderer/vulkan/VertexArrayVk.cpp
    src/libANGLE/renderer/vulkan/VertexArrayVk.h
    src/libANGLE/renderer/vulkan/VkImageImageSiblingVk.cpp
    src/libANGLE/renderer/vulkan/VkImageImageSiblingVk.h
    src/libANGLE/renderer/vulkan/VulkanSecondaryCommandBuffer.cpp
    src/libANGLE/renderer/vulkan/VulkanSecondaryCommandBuffer.h
    src/libANGLE/renderer/vulkan/android/vk_android_utils.cpp
    src/libANGLE/renderer/vulkan/android/vk_android_utils.h
    src/libANGLE/renderer/vulkan/spv_utils.cpp
    src/libANGLE/renderer/vulkan/spv_utils.h
    src/libANGLE/renderer/vulkan/vk_cache_utils.cpp
    src/libANGLE/renderer/vulkan/vk_cache_utils.h
    src/libANGLE/renderer/vulkan/vk_caps_utils.cpp
    src/libANGLE/renderer/vulkan/vk_caps_utils.h
    src/libANGLE/renderer/vulkan/vk_command_buffer_utils.h
    src/libANGLE/renderer/vulkan/vk_format_table_autogen.cpp
    src/libANGLE/renderer/vulkan/vk_format_utils.cpp
    src/libANGLE/renderer/vulkan/vk_format_utils.h
    src/libANGLE/renderer/vulkan/vk_helpers.cpp
    src/libANGLE/renderer/vulkan/vk_helpers.h
    src/libANGLE/renderer/vulkan/vk_internal_shaders_autogen.cpp
    src/libANGLE/renderer/vulkan/vk_internal_shaders_autogen.h
    src/libANGLE/renderer/vulkan/vk_mandatory_format_support_table_autogen.cpp
    src/libANGLE/renderer/vulkan/vk_ref_counted_event.cpp
    src/libANGLE/renderer/vulkan/vk_ref_counted_event.h
    src/libANGLE/renderer/vulkan/vk_renderer.cpp
    src/libANGLE/renderer/vulkan/vk_renderer.h
    src/libANGLE/renderer/vulkan/vk_resource.cpp
    src/libANGLE/renderer/vulkan/vk_resource.h
    src/libANGLE/renderer/vulkan/vk_utils.cpp
    src/libANGLE/renderer/vulkan/vk_utils.h
    src/libANGLE/renderer/vulkan/vk_wrapper.h
)

set(angle_vulkan_backend_sources_win32
    # is_win
    src/libANGLE/renderer/vulkan/win32/DisplayVkWin32.cpp
    src/libANGLE/renderer/vulkan/win32/DisplayVkWin32.h
    src/libANGLE/renderer/vulkan/win32/WindowSurfaceVkWin32.cpp
    src/libANGLE/renderer/vulkan/win32/WindowSurfaceVkWin32.h
)

set(angle_vulkan_backend_sources_x11
    # angle_use_x11
    src/libANGLE/renderer/vulkan/linux/xcb/DisplayVkXcb.cpp
    src/libANGLE/renderer/vulkan/linux/xcb/DisplayVkXcb.h
    src/libANGLE/renderer/vulkan/linux/xcb/WindowSurfaceVkXcb.cpp
    src/libANGLE/renderer/vulkan/linux/xcb/WindowSurfaceVkXcb.h
)

set(angle_vulkan_backend_sources_wayland
    # angle_use_wayland
    src/libANGLE/renderer/vulkan/linux/wayland/DisplayVkWayland.cpp
    src/libANGLE/renderer/vulkan/linux/wayland/DisplayVkWayland.h
    src/libANGLE/renderer/vulkan/linux/wayland/WindowSurfaceVkWayland.cpp
    src/libANGLE/renderer/vulkan/linux/wayland/WindowSurfaceVkWayland.h
)

set(angle_vulkan_backend_sources_gbm
    # angle_use_gbm
    src/libANGLE/renderer/vulkan/linux/gbm/DisplayVkGbm.cpp
    src/libANGLE/renderer/vulkan/linux/gbm/DisplayVkGbm.h
)

set(angle_vulkan_backend_sources_mac
    # is_mac
    src/libANGLE/renderer/vulkan/mac/DisplayVkMac.h
    src/libANGLE/renderer/vulkan/mac/DisplayVkMac.mm
    src/libANGLE/renderer/vulkan/mac/IOSurfaceSurfaceVkMac.h
    src/libANGLE/renderer/vulkan/mac/IOSurfaceSurfaceVkMac.mm
    src/libANGLE/renderer/vulkan/mac/WindowSurfaceVkMac.h
    src/libANGLE/renderer/vulkan/mac/WindowSurfaceVkMac.mm
)

set(angle_d3d_shared_sources
    src/libANGLE/renderer/d3d/BufferD3D.cpp
    src/libANGLE/renderer/d3d/BufferD3D.h
    src/libANGLE/renderer/d3d/CompilerD3D.cpp
    src/libANGLE/renderer/d3d/CompilerD3D.h
    src/libANGLE/renderer/d3d/ContextD3D.h
    src/libANGLE/renderer/d3d/DisplayD3D.cpp
    src/libANGLE/renderer/d3d/DisplayD3D.h
    src/libANGLE/renderer/d3d/DynamicHLSL.cpp
    src/libANGLE/renderer/d3d/DynamicHLSL.h
    src/libANGLE/renderer/d3d/DynamicImage2DHLSL.cpp
    src/libANGLE/renderer/d3d/DynamicImage2DHLSL.h
    src/libANGLE/renderer/d3d/EGLImageD3D.cpp
    src/libANGLE/renderer/d3d/EGLImageD3D.h
    src/libANGLE/renderer/d3d/FramebufferD3D.cpp
    src/libANGLE/renderer/d3d/FramebufferD3D.h
    src/libANGLE/renderer/d3d/HLSLCompiler.cpp
    src/libANGLE/renderer/d3d/HLSLCompiler.h
    src/libANGLE/renderer/d3d/ImageD3D.cpp
    src/libANGLE/renderer/d3d/ImageD3D.h
    src/libANGLE/renderer/d3d/IndexBuffer.cpp
    src/libANGLE/renderer/d3d/IndexBuffer.h
    src/libANGLE/renderer/d3d/IndexDataManager.cpp
    src/libANGLE/renderer/d3d/IndexDataManager.h
    src/libANGLE/renderer/d3d/NativeWindowD3D.cpp
    src/libANGLE/renderer/d3d/NativeWindowD3D.h
    src/libANGLE/renderer/d3d/ProgramD3D.cpp
    src/libANGLE/renderer/d3d/ProgramD3D.h
    src/libANGLE/renderer/d3d/ProgramExecutableD3D.cpp
    src/libANGLE/renderer/d3d/ProgramExecutableD3D.h
    src/libANGLE/renderer/d3d/RenderTargetD3D.cpp
    src/libANGLE/renderer/d3d/RenderTargetD3D.h
    src/libANGLE/renderer/d3d/RenderbufferD3D.cpp
    src/libANGLE/renderer/d3d/RenderbufferD3D.h
    src/libANGLE/renderer/d3d/RendererD3D.cpp
    src/libANGLE/renderer/d3d/RendererD3D.h
    src/libANGLE/renderer/d3d/SamplerD3D.h
    src/libANGLE/renderer/d3d/ShaderD3D.cpp
    src/libANGLE/renderer/d3d/ShaderD3D.h
    src/libANGLE/renderer/d3d/ShaderExecutableD3D.cpp
    src/libANGLE/renderer/d3d/ShaderExecutableD3D.h
    src/libANGLE/renderer/d3d/SurfaceD3D.cpp
    src/libANGLE/renderer/d3d/SurfaceD3D.h
    src/libANGLE/renderer/d3d/SwapChainD3D.cpp
    src/libANGLE/renderer/d3d/SwapChainD3D.h
    src/libANGLE/renderer/d3d/TextureD3D.cpp
    src/libANGLE/renderer/d3d/TextureD3D.h
    src/libANGLE/renderer/d3d/TextureStorage.h
    src/libANGLE/renderer/d3d/VertexBuffer.cpp
    src/libANGLE/renderer/d3d/VertexBuffer.h
    src/libANGLE/renderer/d3d/VertexDataManager.cpp
    src/libANGLE/renderer/d3d/VertexDataManager.h
    src/libANGLE/renderer/d3d/driver_utils_d3d.cpp
    src/libANGLE/renderer/d3d/driver_utils_d3d.h
    src/libANGLE/renderer/d3d/formatutilsD3D.h
)

set(angle_d3d9_backend_sources
    # angle_enable_d3d9
    src/libANGLE/renderer/d3d/d3d9/Blit9.cpp
    src/libANGLE/renderer/d3d/d3d9/Blit9.h
    src/libANGLE/renderer/d3d/d3d9/Buffer9.cpp
    src/libANGLE/renderer/d3d/d3d9/Buffer9.h
    src/libANGLE/renderer/d3d/d3d9/Context9.cpp
    src/libANGLE/renderer/d3d/d3d9/Context9.h
    src/libANGLE/renderer/d3d/d3d9/DebugAnnotator9.cpp
    src/libANGLE/renderer/d3d/d3d9/DebugAnnotator9.h
    src/libANGLE/renderer/d3d/d3d9/Device9.cpp
    src/libANGLE/renderer/d3d/d3d9/Device9.h
    src/libANGLE/renderer/d3d/d3d9/Fence9.cpp
    src/libANGLE/renderer/d3d/d3d9/Fence9.h
    src/libANGLE/renderer/d3d/d3d9/Framebuffer9.cpp
    src/libANGLE/renderer/d3d/d3d9/Framebuffer9.h
    src/libANGLE/renderer/d3d/d3d9/Image9.cpp
    src/libANGLE/renderer/d3d/d3d9/Image9.h
    src/libANGLE/renderer/d3d/d3d9/IndexBuffer9.cpp
    src/libANGLE/renderer/d3d/d3d9/IndexBuffer9.h
    src/libANGLE/renderer/d3d/d3d9/NativeWindow9.cpp
    src/libANGLE/renderer/d3d/d3d9/NativeWindow9.h
    src/libANGLE/renderer/d3d/d3d9/Query9.cpp
    src/libANGLE/renderer/d3d/d3d9/Query9.h
    src/libANGLE/renderer/d3d/d3d9/RenderTarget9.cpp
    src/libANGLE/renderer/d3d/d3d9/RenderTarget9.h
    src/libANGLE/renderer/d3d/d3d9/Renderer9.cpp
    src/libANGLE/renderer/d3d/d3d9/Renderer9.h
    src/libANGLE/renderer/d3d/d3d9/ShaderCache.h
    src/libANGLE/renderer/d3d/d3d9/ShaderExecutable9.cpp
    src/libANGLE/renderer/d3d/d3d9/ShaderExecutable9.h
    src/libANGLE/renderer/d3d/d3d9/StateManager9.cpp
    src/libANGLE/renderer/d3d/d3d9/StateManager9.h
    src/libANGLE/renderer/d3d/d3d9/SwapChain9.cpp
    src/libANGLE/renderer/d3d/d3d9/SwapChain9.h
    src/libANGLE/renderer/d3d/d3d9/TextureStorage9.cpp
    src/libANGLE/renderer/d3d/d3d9/TextureStorage9.h
    src/libANGLE/renderer/d3d/d3d9/VertexArray9.h
    src/libANGLE/renderer/d3d/d3d9/VertexBuffer9.cpp
    src/libANGLE/renderer/d3d/d3d9/VertexBuffer9.h
    src/libANGLE/renderer/d3d/d3d9/VertexDeclarationCache.cpp
    src/libANGLE/renderer/d3d/d3d9/VertexDeclarationCache.h
    src/libANGLE/renderer/d3d/d3d9/formatutils9.cpp
    src/libANGLE/renderer/d3d/d3d9/formatutils9.h
    src/libANGLE/renderer/d3d/d3d9/renderer9_utils.cpp
    src/libANGLE/renderer/d3d/d3d9/renderer9_utils.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/componentmaskpremultps.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/componentmaskps.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/componentmaskunmultps.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/luminancepremultps.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/luminanceps.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/luminanceunmultps.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/passthroughps.h
    src/libANGLE/renderer/d3d/d3d9/shaders/compiled/standardvs.h
    src/libANGLE/renderer/d3d/d3d9/vertexconversion.h
)

set(angle_d3d11_backend_sources
    src/libANGLE/renderer/d3d/d3d11/Blit11.cpp
    src/libANGLE/renderer/d3d/d3d11/Blit11.h
    src/libANGLE/renderer/d3d/d3d11/Blit11Helper_autogen.inc
    src/libANGLE/renderer/d3d/d3d11/Buffer11.cpp
    src/libANGLE/renderer/d3d/d3d11/Buffer11.h
    src/libANGLE/renderer/d3d/d3d11/Clear11.cpp
    src/libANGLE/renderer/d3d/d3d11/Clear11.h
    src/libANGLE/renderer/d3d/d3d11/Context11.cpp
    src/libANGLE/renderer/d3d/d3d11/Context11.h
    src/libANGLE/renderer/d3d/d3d11/DebugAnnotator11.cpp
    src/libANGLE/renderer/d3d/d3d11/DebugAnnotator11.h
    src/libANGLE/renderer/d3d/d3d11/Device11.cpp
    src/libANGLE/renderer/d3d/d3d11/Device11.h
    src/libANGLE/renderer/d3d/d3d11/ExternalImageSiblingImpl11.cpp
    src/libANGLE/renderer/d3d/d3d11/ExternalImageSiblingImpl11.h
    src/libANGLE/renderer/d3d/d3d11/Fence11.cpp
    src/libANGLE/renderer/d3d/d3d11/Fence11.h
    src/libANGLE/renderer/d3d/d3d11/Framebuffer11.cpp
    src/libANGLE/renderer/d3d/d3d11/Framebuffer11.h
    src/libANGLE/renderer/d3d/d3d11/Image11.cpp
    src/libANGLE/renderer/d3d/d3d11/Image11.h
    src/libANGLE/renderer/d3d/d3d11/IndexBuffer11.cpp
    src/libANGLE/renderer/d3d/d3d11/IndexBuffer11.h
    src/libANGLE/renderer/d3d/d3d11/InputLayoutCache.cpp
    src/libANGLE/renderer/d3d/d3d11/InputLayoutCache.h
    src/libANGLE/renderer/d3d/d3d11/MappedSubresourceVerifier11.cpp
    src/libANGLE/renderer/d3d/d3d11/MappedSubresourceVerifier11.h
    src/libANGLE/renderer/d3d/d3d11/NativeWindow11.h
    src/libANGLE/renderer/d3d/d3d11/PixelTransfer11.cpp
    src/libANGLE/renderer/d3d/d3d11/PixelTransfer11.h
    src/libANGLE/renderer/d3d/d3d11/Program11.cpp
    src/libANGLE/renderer/d3d/d3d11/Program11.h
    src/libANGLE/renderer/d3d/d3d11/ProgramPipeline11.cpp
    src/libANGLE/renderer/d3d/d3d11/ProgramPipeline11.h
    src/libANGLE/renderer/d3d/d3d11/Query11.cpp
    src/libANGLE/renderer/d3d/d3d11/Query11.h
    src/libANGLE/renderer/d3d/d3d11/RenderStateCache.cpp
    src/libANGLE/renderer/d3d/d3d11/RenderStateCache.h
    src/libANGLE/renderer/d3d/d3d11/RenderTarget11.cpp
    src/libANGLE/renderer/d3d/d3d11/RenderTarget11.h
    src/libANGLE/renderer/d3d/d3d11/Renderer11.cpp
    src/libANGLE/renderer/d3d/d3d11/Renderer11.h
    src/libANGLE/renderer/d3d/d3d11/ResourceManager11.cpp
    src/libANGLE/renderer/d3d/d3d11/ResourceManager11.h
    src/libANGLE/renderer/d3d/d3d11/ShaderExecutable11.cpp
    src/libANGLE/renderer/d3d/d3d11/ShaderExecutable11.h
    src/libANGLE/renderer/d3d/d3d11/StateManager11.cpp
    src/libANGLE/renderer/d3d/d3d11/StateManager11.h
    src/libANGLE/renderer/d3d/d3d11/StreamProducerD3DTexture.cpp
    src/libANGLE/renderer/d3d/d3d11/StreamProducerD3DTexture.h
    src/libANGLE/renderer/d3d/d3d11/SwapChain11.cpp
    src/libANGLE/renderer/d3d/d3d11/SwapChain11.h
    src/libANGLE/renderer/d3d/d3d11/TextureStorage11.cpp
    src/libANGLE/renderer/d3d/d3d11/TextureStorage11.h
    src/libANGLE/renderer/d3d/d3d11/TransformFeedback11.cpp
    src/libANGLE/renderer/d3d/d3d11/TransformFeedback11.h
    src/libANGLE/renderer/d3d/d3d11/Trim11.cpp
    src/libANGLE/renderer/d3d/d3d11/Trim11.h
    src/libANGLE/renderer/d3d/d3d11/VertexArray11.cpp
    src/libANGLE/renderer/d3d/d3d11/VertexArray11.h
    src/libANGLE/renderer/d3d/d3d11/VertexBuffer11.cpp
    src/libANGLE/renderer/d3d/d3d11/VertexBuffer11.h
    src/libANGLE/renderer/d3d/d3d11/formatutils11.cpp
    src/libANGLE/renderer/d3d/d3d11/formatutils11.h
    src/libANGLE/renderer/d3d/d3d11/renderer11_utils.cpp
    src/libANGLE/renderer/d3d/d3d11/renderer11_utils.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_gs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_ps_4f.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_ps_4i.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_ps_4ui.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/buffertotexture11_vs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clear11multiviewgs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clear11multiviewvs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clear11vs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/cleardepth11ps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps1.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps2.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps3.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps4.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps5.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps6.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps7.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearfloat11ps8.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps1.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps2.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps3.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps4.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps5.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps6.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps7.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearsint11ps8.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps1.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps2.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps3.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps4.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps5.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps6.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps7.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/clearuint11ps8.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthrough2d11vs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthrough3d11gs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthrough3d11vs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthroughdepth2d11ps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/passthroughrgba2dms11ps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvecolor2dps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvedepth11_ps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvedepthstencil11_ps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvedepthstencil11_vs.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/resolvestencil11_ps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlef2darrayps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlef2dps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlef3dps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlei2darrayps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlei2dps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzlei3dps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzleui2darrayps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzleui2dps.h
    src/libANGLE/renderer/d3d/d3d11/shaders/compiled/swizzleui3dps.h
    src/libANGLE/renderer/d3d/d3d11/texture_format_table.cpp
    src/libANGLE/renderer/d3d/d3d11/texture_format_table.h
    src/libANGLE/renderer/d3d/d3d11/texture_format_table_autogen.cpp
    src/libANGLE/renderer/d3d/d3d11/texture_format_table_utils.h
)

set(angle_d3d11_backend_sources_winuwp
    # angle_is_winuwp
    src/libANGLE/renderer/d3d/d3d11/winrt/CoreWindowNativeWindow.cpp
    src/libANGLE/renderer/d3d/d3d11/winrt/CoreWindowNativeWindow.h
    src/libANGLE/renderer/d3d/d3d11/winrt/InspectableNativeWindow.cpp
    src/libANGLE/renderer/d3d/d3d11/winrt/InspectableNativeWindow.h
    src/libANGLE/renderer/d3d/d3d11/winrt/NativeWindow11WinRT.cpp
    src/libANGLE/renderer/d3d/d3d11/winrt/NativeWindow11WinRT.h
    src/libANGLE/renderer/d3d/d3d11/winrt/SwapChainPanelNativeWindow.cpp
    src/libANGLE/renderer/d3d/d3d11/winrt/SwapChainPanelNativeWindow.h
)

set(angle_d3d11_backend_sources_win32
    # !angle_is_winuwp
    src/libANGLE/renderer/d3d/d3d11/win32/NativeWindow11Win32.cpp
    src/libANGLE/renderer/d3d/d3d11/win32/NativeWindow11Win32.h
)

set(angle_d3d11_backend_sources_compositor_native_window
    # angle_enable_d3d11_compositor_native_window
    src/libANGLE/renderer/d3d/d3d11/converged/CompositorNativeWindow11.cpp
    src/libANGLE/renderer/d3d/d3d11/converged/CompositorNativeWindow11.h
)

set(angle_metal_backend_sources
    src/libANGLE/renderer/metal/BufferMtl.h
    src/libANGLE/renderer/metal/BufferMtl.mm
    src/libANGLE/renderer/metal/CompilerMtl.h
    src/libANGLE/renderer/metal/CompilerMtl.mm
    src/libANGLE/renderer/metal/ContextMtl.h
    src/libANGLE/renderer/metal/ContextMtl.mm
    src/libANGLE/renderer/metal/DeviceMtl.h
    src/libANGLE/renderer/metal/DeviceMtl.mm
    src/libANGLE/renderer/metal/DisplayMtl.h
    src/libANGLE/renderer/metal/DisplayMtl.mm
    src/libANGLE/renderer/metal/DisplayMtl_api.h
    src/libANGLE/renderer/metal/FrameBufferMtl.h
    src/libANGLE/renderer/metal/FrameBufferMtl.mm
    src/libANGLE/renderer/metal/IOSurfaceSurfaceMtl.h
    src/libANGLE/renderer/metal/IOSurfaceSurfaceMtl.mm
    src/libANGLE/renderer/metal/ImageMtl.h
    src/libANGLE/renderer/metal/ImageMtl.mm
    src/libANGLE/renderer/metal/ProgramExecutableMtl.h
    src/libANGLE/renderer/metal/ProgramExecutableMtl.mm
    src/libANGLE/renderer/metal/ProgramMtl.h
    src/libANGLE/renderer/metal/ProgramMtl.mm
    src/libANGLE/renderer/metal/ProvokingVertexHelper.h
    src/libANGLE/renderer/metal/ProvokingVertexHelper.mm
    src/libANGLE/renderer/metal/QueryMtl.h
    src/libANGLE/renderer/metal/QueryMtl.mm
    src/libANGLE/renderer/metal/RenderBufferMtl.h
    src/libANGLE/renderer/metal/RenderBufferMtl.mm
    src/libANGLE/renderer/metal/RenderTargetMtl.h
    src/libANGLE/renderer/metal/RenderTargetMtl.mm
    src/libANGLE/renderer/metal/SamplerMtl.h
    src/libANGLE/renderer/metal/SamplerMtl.mm
    src/libANGLE/renderer/metal/ShaderMtl.h
    src/libANGLE/renderer/metal/ShaderMtl.mm
    src/libANGLE/renderer/metal/SurfaceMtl.h
    src/libANGLE/renderer/metal/SurfaceMtl.mm
    src/libANGLE/renderer/metal/SyncMtl.h
    src/libANGLE/renderer/metal/SyncMtl.mm
    src/libANGLE/renderer/metal/TextureMtl.h
    src/libANGLE/renderer/metal/TextureMtl.mm
    src/libANGLE/renderer/metal/TransformFeedbackMtl.h
    src/libANGLE/renderer/metal/TransformFeedbackMtl.mm
    src/libANGLE/renderer/metal/VertexArrayMtl.h
    src/libANGLE/renderer/metal/VertexArrayMtl.mm
    src/libANGLE/renderer/metal/blocklayoutMetal.cpp
    src/libANGLE/renderer/metal/blocklayoutMetal.h
    src/libANGLE/renderer/metal/mtl_buffer_manager.h
    src/libANGLE/renderer/metal/mtl_buffer_manager.mm
    src/libANGLE/renderer/metal/mtl_buffer_pool.h
    src/libANGLE/renderer/metal/mtl_buffer_pool.mm
    src/libANGLE/renderer/metal/mtl_command_buffer.h
    src/libANGLE/renderer/metal/mtl_command_buffer.mm
    src/libANGLE/renderer/metal/mtl_common.h
    src/libANGLE/renderer/metal/mtl_common.mm
    src/libANGLE/renderer/metal/mtl_context_device.h
    src/libANGLE/renderer/metal/mtl_context_device.mm
    src/libANGLE/renderer/metal/mtl_format_table_autogen.mm
    src/libANGLE/renderer/metal/mtl_format_utils.h
    src/libANGLE/renderer/metal/mtl_format_utils.mm
    src/libANGLE/renderer/metal/mtl_library_cache.h
    src/libANGLE/renderer/metal/mtl_library_cache.mm
    src/libANGLE/renderer/metal/mtl_msl_utils.h
    src/libANGLE/renderer/metal/mtl_msl_utils.mm
    src/libANGLE/renderer/metal/mtl_occlusion_query_pool.h
    src/libANGLE/renderer/metal/mtl_occlusion_query_pool.mm
    src/libANGLE/renderer/metal/mtl_pipeline_cache.h
    src/libANGLE/renderer/metal/mtl_pipeline_cache.mm
    src/libANGLE/renderer/metal/mtl_render_utils.h
    src/libANGLE/renderer/metal/mtl_render_utils.mm
    src/libANGLE/renderer/metal/mtl_resource_spi.h
    src/libANGLE/renderer/metal/mtl_resources.h
    src/libANGLE/renderer/metal/mtl_resources.mm
    src/libANGLE/renderer/metal/mtl_state_cache.h
    src/libANGLE/renderer/metal/mtl_state_cache.mm
    src/libANGLE/renderer/metal/mtl_utils.h
    src/libANGLE/renderer/metal/mtl_utils.mm
    src/libANGLE/renderer/metal/renderermtl_utils.cpp
    src/libANGLE/renderer/metal/renderermtl_utils.h
    src/libANGLE/renderer/metal/shaders/constants.h
    src/libANGLE/renderer/metal/shaders/mtl_internal_shaders_src_autogen.h
    src/libANGLE/renderer/metal/shaders/rewrite_indices_shared.h
)

set(angle_wgpu_backend_sources
    src/libANGLE/renderer/wgpu/BufferWgpu.cpp
    src/libANGLE/renderer/wgpu/BufferWgpu.h
    src/libANGLE/renderer/wgpu/CompilerWgpu.cpp
    src/libANGLE/renderer/wgpu/CompilerWgpu.h
    src/libANGLE/renderer/wgpu/ContextWgpu.cpp
    src/libANGLE/renderer/wgpu/ContextWgpu.h
    src/libANGLE/renderer/wgpu/DeviceWgpu.cpp
    src/libANGLE/renderer/wgpu/DeviceWgpu.h
    src/libANGLE/renderer/wgpu/DisplayWgpu.cpp
    src/libANGLE/renderer/wgpu/DisplayWgpu.h
    src/libANGLE/renderer/wgpu/DisplayWgpu_api.h
    src/libANGLE/renderer/wgpu/FenceNVWgpu.cpp
    src/libANGLE/renderer/wgpu/FenceNVWgpu.h
    src/libANGLE/renderer/wgpu/FramebufferWgpu.cpp
    src/libANGLE/renderer/wgpu/FramebufferWgpu.h
    src/libANGLE/renderer/wgpu/ImageWgpu.cpp
    src/libANGLE/renderer/wgpu/ImageWgpu.h
    src/libANGLE/renderer/wgpu/ProgramExecutableWgpu.cpp
    src/libANGLE/renderer/wgpu/ProgramExecutableWgpu.h
    src/libANGLE/renderer/wgpu/ProgramPipelineWgpu.cpp
    src/libANGLE/renderer/wgpu/ProgramPipelineWgpu.h
    src/libANGLE/renderer/wgpu/ProgramWgpu.cpp
    src/libANGLE/renderer/wgpu/ProgramWgpu.h
    src/libANGLE/renderer/wgpu/QueryWgpu.cpp
    src/libANGLE/renderer/wgpu/QueryWgpu.h
    src/libANGLE/renderer/wgpu/RenderTargetWgpu.cpp
    src/libANGLE/renderer/wgpu/RenderTargetWgpu.h
    src/libANGLE/renderer/wgpu/RenderbufferWgpu.cpp
    src/libANGLE/renderer/wgpu/RenderbufferWgpu.h
    src/libANGLE/renderer/wgpu/SamplerWgpu.cpp
    src/libANGLE/renderer/wgpu/SamplerWgpu.h
    src/libANGLE/renderer/wgpu/ShaderWgpu.cpp
    src/libANGLE/renderer/wgpu/ShaderWgpu.h
    src/libANGLE/renderer/wgpu/SurfaceWgpu.cpp
    src/libANGLE/renderer/wgpu/SurfaceWgpu.h
    src/libANGLE/renderer/wgpu/SyncWgpu.cpp
    src/libANGLE/renderer/wgpu/SyncWgpu.h
    src/libANGLE/renderer/wgpu/TextureWgpu.cpp
    src/libANGLE/renderer/wgpu/TextureWgpu.h
    src/libANGLE/renderer/wgpu/TransformFeedbackWgpu.cpp
    src/libANGLE/renderer/wgpu/TransformFeedbackWgpu.h
    src/libANGLE/renderer/wgpu/VertexArrayWgpu.cpp
    src/libANGLE/renderer/wgpu/VertexArrayWgpu.h
    src/libANGLE/renderer/wgpu/wgpu_command_buffer.cpp
    src/libANGLE/renderer/wgpu/wgpu_command_buffer.h
    src/libANGLE/renderer/wgpu/wgpu_format_table_autogen.cpp
    src/libANGLE/renderer/wgpu/wgpu_format_utils.cpp
    src/libANGLE/renderer/wgpu/wgpu_format_utils.h
    src/libANGLE/renderer/wgpu/wgpu_helpers.cpp
    src/libANGLE/renderer/wgpu/wgpu_helpers.h
    src/libANGLE/renderer/wgpu/wgpu_pipeline_state.cpp
    src/libANGLE/renderer/wgpu/wgpu_pipeline_state.h
    src/libANGLE/renderer/wgpu/wgpu_utils.cpp
    src/libANGLE/renderer/wgpu/wgpu_utils.h
    src/libANGLE/renderer/wgpu/wgpu_wgsl_util.cpp
    src/libANGLE/renderer/wgpu/wgpu_wgsl_util.h
)

set(angle_wgpu_backend_sources_win32
    # is_win
    src/libANGLE/renderer/wgpu/win32/WindowSurfaceWgpuWin32.cpp
    src/libANGLE/renderer/wgpu/win32/WindowSurfaceWgpuWin32.h
)

set(angle_wgpu_backend_sources_mac
    # is_mac
    src/libANGLE/renderer/wgpu/mac/WindowSurfaceWgpuMetalLayer.h
    src/libANGLE/renderer/wgpu/mac/WindowSurfaceWgpuMetalLayer.mm
)

set(angle_wgpu_backend_sources_x11
    # angle_use_x11
    src/libANGLE/renderer/wgpu/linux/x11/WindowSurfaceWgpuX11.cpp
    src/libANGLE/renderer/wgpu/linux/x11/WindowSurfaceWgpuX11.h
)

# src/libGLESv2.gni

set(angle_libangle_common_headers
    src/common/BinaryStream.h
    src/common/CircularBuffer.h
    src/common/Color.h
    src/common/Color.inc
    src/common/CompiledShaderState.h
    src/common/FastVector.h
    src/common/FixedQueue.h
    src/common/FixedVector.h
    src/common/MemoryBuffer.h
    src/common/Optional.h
    src/common/PackedEGLEnums_autogen.h
    src/common/PackedEnums.h
    src/common/PackedGLEnums_autogen.h
    src/common/PackedCLEnums_autogen.h
    src/common/PoolAlloc.h
    src/common/RingBufferAllocator.h
    src/common/SimpleMutex.h
    src/common/SynchronizedValue.h
    src/common/WorkerThread.h
    src/common/aligned_memory.h
    src/common/android_util.h
    src/common/angleutils.h
    src/common/apple_platform_utils.h
    src/common/backtrace_utils.h
    src/common/base/anglebase/base_export.h
    src/common/base/anglebase/containers/mru_cache.h
    src/common/base/anglebase/logging.h
    src/common/base/anglebase/macros.h
    src/common/base/anglebase/no_destructor.h
    src/common/base/anglebase/numerics/checked_math.h
    src/common/base/anglebase/numerics/checked_math_impl.h
    src/common/base/anglebase/numerics/clamped_math.h
    src/common/base/anglebase/numerics/clamped_math_impl.h
    src/common/base/anglebase/numerics/math_constants.h
    src/common/base/anglebase/numerics/ranges.h
    src/common/base/anglebase/numerics/safe_conversions.h
    src/common/base/anglebase/numerics/safe_conversions_arm_impl.h
    src/common/base/anglebase/numerics/safe_conversions_impl.h
    src/common/base/anglebase/numerics/safe_math.h
    src/common/base/anglebase/numerics/safe_math_arm_impl.h
    src/common/base/anglebase/numerics/safe_math_clang_gcc_impl.h
    src/common/base/anglebase/numerics/safe_math_shared_impl.h
    src/common/base/anglebase/sha1.h
    src/common/base/anglebase/sys_byteorder.h
    src/common/bitset_utils.h
    src/common/debug.h
    src/common/entry_points_enum_autogen.h
    src/common/event_tracer.h
    src/common/hash_containers.h
    src/common/hash_utils.h
    src/common/log_utils.h
    src/common/mathutil.h
    src/common/matrix_utils.h
    src/common/platform.h
    src/common/platform_helpers.h
    src/common/span.h
    src/common/string_utils.h
    src/common/system_utils.h
    src/common/tls.h
    src/common/uniform_type_info_autogen.h
    src/common/utilities.h
    src/common/vector_utils.h
    src/libANGLE/CLBitField.h
)

set(angle_libangle_common_sources
    ${angle_libangle_common_headers}
    src/common/Float16ToFloat32.cpp
    src/common/MemoryBuffer.cpp
    src/common/PackedEGLEnums_autogen.cpp
    src/common/PackedEnums.cpp
    src/common/PackedGLEnums_autogen.cpp
    src/common/PoolAlloc.cpp
    src/common/RingBufferAllocator.cpp
    src/common/SimpleMutex.cpp
    src/common/WorkerThread.cpp
    src/common/aligned_memory.cpp
    src/common/android_util.cpp
    src/common/angleutils.cpp
    src/common/base/anglebase/sha1.cc
    src/common/debug.cpp
    src/common/entry_points_enum_autogen.cpp
    src/common/event_tracer.cpp
    src/common/mathutil.cpp
    src/common/matrix_utils.cpp
    src/common/platform_helpers.cpp
    src/common/string_utils.cpp
    src/common/system_utils.cpp
    src/common/tls.cpp
    src/common/uniform_type_info_autogen.cpp
    src/common/utilities.cpp
    # !angle_enable_unwind_backtrace_support
    src/common/backtrace_utils_noop.cpp
)

set(angle_libangle_common_shader_state_sources
    ${angle_libangle_common_headers}
    src/common/CompiledShaderState.cpp
)

set(angle_xxhash_sources
    src/common/third_party/xxhash/xxhash.c
    src/common/third_party/xxhash/xxhash.h
)

set(angle_libangle_common_sources_linux
    # is_linux || is_chromeos || is_android || is_fuchsia
    src/common/system_utils_linux.cpp
    src/common/system_utils_posix.cpp
)

set(angle_libangle_common_sources_apple
    # is_apple
    src/common/apple/ObjCPtr.h
    src/common/apple/SoftLinking.h
    src/common/apple/apple_platform.h
    src/common/apple_platform_utils.mm
    src/common/system_utils_apple.cpp
    src/common/system_utils_posix.cpp
)

set(angle_libangle_common_sources_mac
    # is_mac
    src/common/gl/cgl/FunctionsCGL.cpp
    src/common/gl/cgl/FunctionsCGL.h
    src/common/system_utils_mac.cpp
)

set(angle_libangle_common_sources_ios
    # is_ios
    src/common/system_utils_ios.cpp
)

set(angle_libangle_common_sources_winuwp
    src/common/system_utils_win.cpp
    src/common/system_utils_winuwp.cpp
)

set(angle_libangle_common_sources_win32
    src/common/system_utils_win.cpp
    src/common/system_utils_win32.cpp
)

set(angle_libangle_image_util_headers
    src/image_util/AstcDecompressor.h
    src/image_util/copyimage.h
    src/image_util/copyimage.inc
    src/image_util/generatemip.h
    src/image_util/generatemip.inc
    src/image_util/imageformats.h
    src/image_util/loadimage.h
    src/image_util/loadimage.inc
    src/image_util/storeimage.h
)

set(angle_libangle_image_util_sources
    src/image_util/copyimage.cpp
    src/image_util/imageformats.cpp
    src/image_util/loadimage.cpp
    src/image_util/loadimage_astc.cpp
    src/image_util/loadimage_etc.cpp
    src/image_util/loadimage_paletted.cpp
    src/image_util/storeimage_paletted.cpp
    # !angle_has_astc_encoder
    src/image_util/AstcDecompressorNoOp.cpp
)

set(angle_libangle_libangle_gpu_info_util_sources
    src/gpu_info_util/SystemInfo.cpp
    src/gpu_info_util/SystemInfo.h
    src/gpu_info_util/SystemInfo_internal.h
)

set(angle_libangle_gpu_info_util_win_sources
    src/gpu_info_util/SystemInfo_win.cpp
)

set(angle_libangle_gpu_info_util_android_sources
    src/gpu_info_util/SystemInfo_android.cpp
)

set(angle_libangle_gpu_info_util_linux_sources
    src/gpu_info_util/SystemInfo_linux.cpp
)

set(angle_libangle_gpu_info_util_vulkan_sources
    src/gpu_info_util/SystemInfo_vulkan.cpp
    src/gpu_info_util/SystemInfo_vulkan.h
)
set(angle_libangle_gpu_info_util_libpci_sources
    src/gpu_info_util/SystemInfo_libpci.cpp
)

set(angle_libangle_gpu_info_util_x11_sources
    src/gpu_info_util/SystemInfo_x11.cpp
)

set(angle_libangle_gpu_info_util_mac_sources
    src/gpu_info_util/SystemInfo_apple.mm
    src/gpu_info_util/SystemInfo_macos.mm
)

set(angle_libangle_gpu_info_util_ios_sources
    src/gpu_info_util/SystemInfo_apple.mm
    src/gpu_info_util/SystemInfo_ios.cpp
)

set(angle_libangle_includes
    include/angle_gl.h
    include/export.h
    include/EGL/egl.h
    include/EGL/eglext.h
    include/EGL/eglext_angle.h
    include/EGL/eglplatform.h
    include/GLES/gl.h
    include/GLES/glplatform.h
    include/GLES/glext.h
    include/GLES2/gl2.h
    include/GLES2/gl2ext.h
    include/GLES2/gl2ext_angle.h
    include/GLES2/gl2platform.h
    include/GLES3/gl3.h
    include/GLES3/gl3platform.h
    include/GLES3/gl31.h
    include/GLES3/gl32.h
    include/GLX/glxext.h
    include/KHR/khrplatform.h
    include/WGL/wgl.h
    include/platform/Feature.h
    include/platform/autogen/FeaturesD3D_autogen.h
    include/platform/autogen/FeaturesGL_autogen.h
    include/platform/autogen/FeaturesMtl_autogen.h
    include/platform/autogen/FeaturesVk_autogen.h
    include/platform/autogen/FrontendFeatures_autogen.h
    include/platform/PlatformMethods.h
    include/vulkan/vulkan_fuchsia_ext.h
)

set(angle_libangle_headers
    src/libANGLE/AttributeMap.h
    src/libANGLE/BlobCache.h
    src/libANGLE/Buffer.h
    src/libANGLE/Caps.h
    src/libANGLE/CLBitField.h
    src/libANGLE/CLRefPointer.h
    src/libANGLE/Compiler.h
    src/libANGLE/Config.h
    src/libANGLE/Constants.h
    src/libANGLE/Context.h
    src/libANGLE/Context.inl.h
    src/libANGLE/Context_gles_1_0_autogen.h
    src/libANGLE/Context_gles_2_0_autogen.h
    src/libANGLE/Context_gles_3_0_autogen.h
    src/libANGLE/Context_gles_3_1_autogen.h
    src/libANGLE/Context_gles_3_2_autogen.h
    src/libANGLE/Context_gles_ext_autogen.h
    src/libANGLE/Debug.h
    src/libANGLE/Device.h
    src/libANGLE/Display.h
    src/libANGLE/EGLSync.h
    src/libANGLE/Error.h
    src/libANGLE/Error.inc
    src/libANGLE/ErrorStrings.h
    src/libANGLE/Fence.h
    src/libANGLE/Framebuffer.h
    src/libANGLE/FramebufferAttachment.h
    src/libANGLE/GLES1Renderer.h
    src/libANGLE/GLES1Shaders.inc
    src/libANGLE/GLES1State.h
    src/libANGLE/GlobalMutex.h
    src/libANGLE/HandleAllocator.h
    src/libANGLE/Image.h
    src/libANGLE/ImageIndex.h
    src/libANGLE/IndexRangeCache.h
    src/libANGLE/InfoLog.h
    src/libANGLE/LoggingAnnotator.h
    src/libANGLE/MemoryObject.h
    src/libANGLE/MemoryProgramCache.h
    src/libANGLE/MemoryShaderCache.h
    src/libANGLE/Observer.h
    src/libANGLE/Overlay.h
    src/libANGLE/OverlayWidgets.h
    src/libANGLE/Overlay_autogen.h
    src/libANGLE/Overlay_font_autogen.h
    src/libANGLE/PixelLocalStorage.h
    src/libANGLE/Program.h
    src/libANGLE/ProgramExecutable.h
    src/libANGLE/ProgramLinkedResources.h
    src/libANGLE/ProgramPipeline.h
    src/libANGLE/Query.h
    src/libANGLE/RefCountObject.h
    src/libANGLE/Renderbuffer.h
    src/libANGLE/ResourceManager.h
    src/libANGLE/ResourceMap.h
    src/libANGLE/Sampler.h
    src/libANGLE/Semaphore.h
    src/libANGLE/Shader.h
    src/libANGLE/ShareGroup.h
    src/libANGLE/ContextMutex.h
    src/libANGLE/SizedMRUCache.h
    src/libANGLE/State.h
    src/libANGLE/Stream.h
    src/libANGLE/Surface.h
    src/libANGLE/Texture.h
    src/libANGLE/Thread.h
    src/libANGLE/TransformFeedback.h
    src/libANGLE/Uniform.h
    src/libANGLE/VaryingPacking.h
    src/libANGLE/Version.h
    src/libANGLE/Version.inc
    src/libANGLE/VertexArray.h
    src/libANGLE/VertexAttribute.h
    src/libANGLE/VertexAttribute.inc
    src/libANGLE/angletypes.h
    src/libANGLE/angletypes.inc
    src/libANGLE/cl_types.h
    src/libANGLE/context_private_call.inl.h
    src/libANGLE/context_private_call_autogen.h
    src/libANGLE/entry_points_utils.cpp
    src/libANGLE/entry_points_utils.h
    src/libANGLE/features.h
    src/libANGLE/formatutils.h
    src/libANGLE/gles_extensions_autogen.h
    src/libANGLE/histogram_macros.h
    src/libANGLE/queryconversions.h
    src/libANGLE/queryutils.h
    src/libANGLE/trace.h
    src/libANGLE/renderer/BufferImpl.h
    src/libANGLE/renderer/CompilerImpl.h
    src/libANGLE/renderer/ContextImpl.h
    src/libANGLE/renderer/driver_utils.h
    src/libANGLE/renderer/DeviceImpl.h
    src/libANGLE/renderer/DisplayImpl.h
    src/libANGLE/renderer/EGLImplFactory.h
    src/libANGLE/renderer/EGLReusableSync.h
    src/libANGLE/renderer/EGLSyncImpl.h
    src/libANGLE/renderer/FenceNVImpl.h
    src/libANGLE/renderer/FormatID_autogen.h
    src/libANGLE/renderer/Format.h
    src/libANGLE/renderer/FramebufferAttachmentObjectImpl.h
    src/libANGLE/renderer/FramebufferImpl.h
    src/libANGLE/renderer/GLImplFactory.h
    src/libANGLE/renderer/gl/functionsgl_enums.h
    src/libANGLE/renderer/ImageImpl.h
    src/libANGLE/renderer/MemoryObjectImpl.h
    src/libANGLE/renderer/OverlayImpl.h
    src/libANGLE/renderer/ProgramImpl.h
    src/libANGLE/renderer/ProgramExecutableImpl.h
    src/libANGLE/renderer/ProgramPipelineImpl.h
    src/libANGLE/renderer/QueryImpl.h
    src/libANGLE/renderer/RenderbufferImpl.h
    src/libANGLE/renderer/RenderTargetCache.h
    src/libANGLE/renderer/SamplerImpl.h
    src/libANGLE/renderer/SemaphoreImpl.h
    src/libANGLE/renderer/ShaderImpl.h
    src/libANGLE/renderer/ShareGroupImpl.h
    src/libANGLE/renderer/StreamProducerImpl.h
    src/libANGLE/renderer/SurfaceImpl.h
    src/libANGLE/renderer/SyncImpl.h
    src/libANGLE/renderer/TransformFeedbackImpl.h
    src/libANGLE/renderer/VertexArrayImpl.h
    src/libANGLE/renderer/vulkan/DisplayVk_api.h
    src/libANGLE/renderer/copyvertex.h
    src/libANGLE/renderer/copyvertex.inc.h
    src/libANGLE/renderer/load_functions_table.h
    src/libANGLE/renderer/renderer_utils.h
    src/libANGLE/renderer/serial_utils.h
    src/libANGLE/validationEGL.h
    src/libANGLE/validationEGL_autogen.h
    src/libANGLE/validationES.h
    src/libANGLE/validationES1.h
    src/libANGLE/validationES1_autogen.h
    src/libANGLE/validationES2.h
    src/libANGLE/validationES2_autogen.h
    src/libANGLE/validationES3.h
    src/libANGLE/validationES31.h
    src/libANGLE/validationES31_autogen.h
    src/libANGLE/validationES32.h
    src/libANGLE/validationES32_autogen.h
    src/libANGLE/validationES3_autogen.h
    src/libANGLE/validationESEXT.h
    src/libANGLE/validationESEXT_autogen.h
    src/common/base/anglebase/trace_event/trace_event.h
    src/libANGLE/CLPlatform.h
    src/libANGLE/renderer/CLPlatformImpl.h
    src/libANGLE/CLObject.h
    src/libANGLE/renderer/CLContextImpl.h
    src/libANGLE/renderer/CLDeviceImpl.h
    src/libANGLE/renderer/CLExtensions.h
    src/libANGLE/renderer/CLCommandQueueImpl.h
    src/libANGLE/renderer/CLEventImpl.h
    src/libANGLE/renderer/CLMemoryImpl.h
    src/libANGLE/renderer/CLProgramImpl.h
    src/libANGLE/renderer/CLSamplerImpl.h
    src/libANGLE/renderer/CLKernelImpl.h
)

set(angle_libangle_sources
    src/libANGLE/AttributeMap.cpp
    src/libANGLE/BlobCache.cpp
    src/libANGLE/Buffer.cpp
    src/libANGLE/Caps.cpp
    src/libANGLE/Compiler.cpp
    src/libANGLE/Config.cpp
    src/libANGLE/Context.cpp
    src/libANGLE/ContextMutex.cpp
    src/libANGLE/Context_gles_1_0.cpp
    src/libANGLE/Debug.cpp
    src/libANGLE/Device.cpp
    src/libANGLE/Display.cpp
    src/libANGLE/EGLSync.cpp
    src/libANGLE/Error.cpp
    src/libANGLE/Fence.cpp
    src/libANGLE/Framebuffer.cpp
    src/libANGLE/FramebufferAttachment.cpp
    src/libANGLE/GLES1Renderer.cpp
    src/libANGLE/GLES1State.cpp
    src/libANGLE/GlobalMutex.cpp
    src/libANGLE/HandleAllocator.cpp
    src/libANGLE/Image.cpp
    src/libANGLE/ImageIndex.cpp
    src/libANGLE/IndexRangeCache.cpp
    src/libANGLE/LoggingAnnotator.cpp
    src/libANGLE/MemoryObject.cpp
    src/libANGLE/MemoryProgramCache.cpp
    src/libANGLE/MemoryShaderCache.cpp
    src/libANGLE/Observer.cpp
    src/libANGLE/Overlay.cpp
    src/libANGLE/OverlayWidgets.cpp
    src/libANGLE/Overlay_autogen.cpp
    src/libANGLE/Overlay_font_autogen.cpp
    src/libANGLE/PixelLocalStorage.cpp
    src/libANGLE/Platform.cpp
    src/libANGLE/Program.cpp
    src/libANGLE/ProgramExecutable.cpp
    src/libANGLE/ProgramLinkedResources.cpp
    src/libANGLE/ProgramPipeline.cpp
    src/libANGLE/Query.cpp
    src/libANGLE/Renderbuffer.cpp
    src/libANGLE/ResourceManager.cpp
    src/libANGLE/Sampler.cpp
    src/libANGLE/Semaphore.cpp
    src/libANGLE/Shader.cpp
    src/libANGLE/ShareGroup.cpp
    src/libANGLE/State.cpp
    src/libANGLE/Stream.cpp
    src/libANGLE/Surface.cpp
    src/libANGLE/Texture.cpp
    src/libANGLE/Thread.cpp
    src/libANGLE/TransformFeedback.cpp
    src/libANGLE/Uniform.cpp
    src/libANGLE/VaryingPacking.cpp
    src/libANGLE/VertexArray.cpp
    src/libANGLE/VertexAttribute.cpp
    src/libANGLE/angletypes.cpp
    src/libANGLE/es3_copy_conversion_table_autogen.cpp
    src/libANGLE/format_map_autogen.cpp
    src/libANGLE/formatutils.cpp
    src/libANGLE/gles_extensions_autogen.cpp
    src/libANGLE/queryconversions.cpp
    src/libANGLE/queryutils.cpp
    src/libANGLE/renderer/BufferImpl.cpp
    src/libANGLE/renderer/ContextImpl.cpp
    src/libANGLE/renderer/DeviceImpl.cpp
    src/libANGLE/renderer/DisplayImpl.cpp
    src/libANGLE/renderer/EGLReusableSync.cpp
    src/libANGLE/renderer/EGLSyncImpl.cpp
    src/libANGLE/renderer/Format_table_autogen.cpp
    src/libANGLE/renderer/FramebufferImpl.cpp
    src/libANGLE/renderer/ImageImpl.cpp
    src/libANGLE/renderer/ProgramImpl.cpp
    src/libANGLE/renderer/ProgramPipelineImpl.cpp
    src/libANGLE/renderer/QueryImpl.cpp
    src/libANGLE/renderer/RenderbufferImpl.cpp
    src/libANGLE/renderer/ShaderImpl.cpp
    src/libANGLE/renderer/SurfaceImpl.cpp
    src/libANGLE/renderer/TextureImpl.cpp
    src/libANGLE/renderer/TransformFeedbackImpl.cpp
    src/libANGLE/renderer/VertexArrayImpl.cpp
    src/libANGLE/renderer/driver_utils.cpp
    src/libANGLE/renderer/load_functions_table_autogen.cpp
    src/libANGLE/renderer/renderer_utils.cpp
    src/libANGLE/validationEGL.cpp
    src/libANGLE/validationES.cpp
    src/libANGLE/validationES1.cpp
    src/libANGLE/validationES2.cpp
    src/libANGLE/validationES3.cpp
    src/libANGLE/validationES31.cpp
    src/libANGLE/validationES32.cpp
    src/libANGLE/validationESEXT.cpp
)

set(angle_libglesv2_sources
    src/libGLESv2/egl_context_lock_autogen.h
    src/libGLESv2/egl_context_lock_impl.h
    src/libGLESv2/egl_ext_stubs.cpp
    src/libGLESv2/egl_ext_stubs_autogen.h
    src/libGLESv2/egl_stubs.cpp
    src/libGLESv2/egl_stubs_autogen.h
    src/libGLESv2/egl_stubs_getprocaddress_autogen.cpp
    src/libGLESv2/entry_points_egl_autogen.cpp
    src/libGLESv2/entry_points_egl_autogen.h
    src/libGLESv2/entry_points_egl_ext_autogen.cpp
    src/libGLESv2/entry_points_egl_ext_autogen.h
    src/libGLESv2/entry_points_gles_1_0_autogen.cpp
    src/libGLESv2/entry_points_gles_1_0_autogen.h
    src/libGLESv2/entry_points_gles_2_0_autogen.cpp
    src/libGLESv2/entry_points_gles_2_0_autogen.h
    src/libGLESv2/entry_points_gles_3_0_autogen.cpp
    src/libGLESv2/entry_points_gles_3_0_autogen.h
    src/libGLESv2/entry_points_gles_3_1_autogen.cpp
    src/libGLESv2/entry_points_gles_3_1_autogen.h
    src/libGLESv2/entry_points_gles_3_2_autogen.cpp
    src/libGLESv2/entry_points_gles_3_2_autogen.h
    src/libGLESv2/entry_points_gles_ext_autogen.cpp
    src/libGLESv2/entry_points_gles_ext_autogen.h
    src/libGLESv2/global_state.cpp
    src/libGLESv2/global_state.h
    src/libGLESv2/libGLESv2_autogen.cpp
    src/libGLESv2/resource.h
)

set(angle_libglesv1_cm_sources
    src/libGLESv1_CM/libGLESv1_CM.cpp
    src/libGLESv1_CM/resource.h
)

set(angle_libegl_sources
    src/libEGL/egl_loader_autogen.h
    src/libEGL/libEGL_autogen.cpp
    src/libEGL/resource.h
    src/libGLESv2/entry_points_egl_autogen.h
    src/libGLESv2/entry_points_egl_ext_autogen.h
)
